apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-platform-ingress
  namespace: resume-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - resume.yourdomain.com
      secretName: resume-tls
  rules:
    - host: resume.yourdomain.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8050
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
